"use client";
import { useState } from "react";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";

type Row={source:string;rank:number;score?:number;title?:string;snippet:string;file?:string;symbol?:string;metadata:Record<string,unknown>};
const tone:Record<string,"blue"|"green"|"amber"|"cyan"|"violet"|"gray">={memory:"green",kb:"amber",project:"blue",codegraph:"cyan"};
export default function RetrievalDebuggerPage(){const[query,setQuery]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<{query:string;counts:Record<string,number>;rows:Row[]}|null>(null);
 const run=async()=>{if(!query.trim())return;setLoading(true);setError("");setResult(null);try{const res=await fetch("/api/retrieval-debugger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})});const json=await res.json();if(!res.ok||json.error){setError(json.error||`HTTP ${res.status}`);return;}setResult(json);}catch(e){setError(String(e));}finally{setLoading(false);}};
 const sources=result?Object.keys(result.counts):[];
 return <div className="space-y-6"><PageHeader eyebrow="retrieval observability" title="Retrieval Debugger" accent="cyan" description="Inspect what RecallOS retrieves from Memory, Knowledge Base, and Project Brain for one query." actions={<StatusPill tone="cyan">source/rank trace</StatusPill>}/><CommandBar><div className="grid gap-3 md:grid-cols-[1fr_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} placeholder="Search memory, KB, and Project Brain..."/><button className="btn btn-primary" disabled={!query.trim()||loading} onClick={run}>{loading?"Searching":"Run retrieval"}</button></div></CommandBar>{error&&<DataCard className="border-rose-500/40 text-rose-300"><SectionTitle title="Retrieval failed"/><pre className="whitespace-pre-wrap text-sm">{error}</pre></DataCard>}{result&&<><div className="grid gap-4 md:grid-cols-4"><MetricTile label="Rows" value={result.rows.length} tone="cyan"/><MetricTile label="Memory" value={result.counts.memory||0} tone="green"/><MetricTile label="KB" value={result.counts.kb||0} tone="amber"/><MetricTile label="Project" value={result.counts.project||0} tone="blue"/></div><div className="grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><DataCard><SectionTitle title="Source summary" subtitle={`Query: ${result.query}`}/><div className="space-y-3">{sources.map(s=><div key={s} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><StatusPill tone={tone[s]||"gray"}>{s}</StatusPill><span className="metric-value font-black text-slate-100">{result.counts[s]}</span></div></div>)}</div></DataCard><DataCard glow><SectionTitle title="Ranked rows" subtitle="Normalized snippets with raw metadata"/><div className="grid max-h-[680px] gap-3 overflow-auto pr-1">{result.rows.map((r,i)=><div key={i} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={tone[r.source]||"gray"}>{r.source}</StatusPill><span className="font-mono text-xs text-slate-500">rank {r.rank}</span>{r.score!==undefined&&<span className="font-mono text-xs text-emerald-300">score {r.score}</span>}</div><h3 className="mt-3 font-black text-slate-100">{r.title||"Untitled"}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-400">{r.snippet}</p><pre className="mt-3 max-h-32 overflow-auto rounded-xl bg-black/30 p-3 text-xs text-slate-500">{JSON.stringify(r.metadata,null,2)}</pre></div>)}</div></DataCard></div></>}{!result&&!loading&&!error&&<EmptyState icon="⬡" title="No retrieval run" description="Run a query to inspect RecallOS retrieval sources, ranks, and snippets."/>}</div>}
