import { withPg } from '../../runtime/pg.mjs';
const q = (sql, params = []) => withPg((client) => client.query(sql, params).then((r) => r.rows));

export async function ensureWorkflowStateSchema(){
 await q(`CREATE TABLE IF NOT EXISTS workflow_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), goal TEXT NOT NULL, status TEXT DEFAULT 'running', current_phase TEXT, workspace_id TEXT DEFAULT 'default', project_id TEXT DEFAULT 'default', metadata_json JSONB DEFAULT '{}'::jsonb, started_at TIMESTAMPTZ DEFAULT NOW(), finished_at TIMESTAMPTZ, result_summary TEXT, error TEXT)`);
 await q(`CREATE TABLE IF NOT EXISTS workflow_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), run_id UUID REFERENCES workflow_runs(id) ON DELETE CASCADE, agent_id TEXT, step_name TEXT NOT NULL, status TEXT DEFAULT 'running', model_id TEXT, provider_id TEXT, handoff_id TEXT, input_summary TEXT, output_summary TEXT, error TEXT, metadata_json JSONB DEFAULT '{}'::jsonb, started_at TIMESTAMPTZ DEFAULT NOW(), finished_at TIMESTAMPTZ)`);
}
export async function workflowRunStart(args){await ensureWorkflowStateSchema();const r=await q(`INSERT INTO workflow_runs (goal,current_phase,workspace_id,project_id,metadata_json) VALUES ($1,$2,$3,$4,$5) RETURNING *`,[args.goal,args.current_phase||'intake',args.workspace_id||'default',args.project_id||'default',args.metadata||{}]);return JSON.stringify(r[0],null,2)}
export async function workflowStepStart(args){await ensureWorkflowStateSchema();const r=await q(`INSERT INTO workflow_steps (run_id,agent_id,step_name,model_id,provider_id,handoff_id,input_summary,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[args.run_id,args.agent_id,args.step_name,args.model_id,args.provider_id,args.handoff_id,args.input_summary,args.metadata||{}]);await q(`UPDATE workflow_runs SET current_phase=$2 WHERE id=$1`,[args.run_id,args.step_name]);return JSON.stringify(r[0],null,2)}
export async function workflowStepUpdate(args){await ensureWorkflowStateSchema();const r=await q(`UPDATE workflow_steps SET status=COALESCE($2,status), output_summary=COALESCE($3,output_summary), error=COALESCE($4,error), finished_at=CASE WHEN $2 IN ('completed','failed','cancelled') THEN NOW() ELSE finished_at END WHERE id=$1 RETURNING *`,[args.step_id,args.status,args.output_summary,args.error]);return JSON.stringify(r[0],null,2)}
export async function workflowRunFinish(args){await ensureWorkflowStateSchema();const r=await q(`UPDATE workflow_runs SET status=$2,result_summary=$3,error=$4,finished_at=NOW() WHERE id=$1 RETURNING *`,[args.run_id,args.status||'completed',args.result_summary,args.error]);return JSON.stringify(r[0],null,2)}
export async function workflowRunList(args={}){await ensureWorkflowStateSchema();const r=await q(`SELECT r.*, COUNT(s.id)::int AS step_count FROM workflow_runs r LEFT JOIN workflow_steps s ON s.run_id=r.id WHERE ($1::text IS NULL OR r.status=$1) GROUP BY r.id ORDER BY r.started_at DESC LIMIT $2`,[args.status||null,args.limit||50]);return JSON.stringify({runs:r},null,2)}
export async function workflowRunGet(args){await ensureWorkflowStateSchema();const runs=await q(`SELECT * FROM workflow_runs WHERE id=$1`,[args.run_id]);const steps=await q(`SELECT * FROM workflow_steps WHERE run_id=$1 ORDER BY started_at`,[args.run_id]);return JSON.stringify({run:runs[0]||null,steps},null,2)}
