"use client";
import { useEffect, useMemo, useState, useCallback } from "react";
import { CommandBar, DataCard, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";

type Provider={id:string;name:string;base_url:string;api_key_masked?:string;api_key_env_var?:string;has_api_key:boolean;api_key_storage:string;status:string};
type Model={id:string;provider_id:string;provider_name?:string;model_id:string;prefix?:string;family?:string;status:string};
type Assignment={id:string;agent_id:string;provider_id:string;provider_name:string;model_id:string;purpose:string;base_url:string;api_key_masked?:string};
const AGENTS=["pm_architecture","analyzer","senior_product_designer","senior_product_coder","product_code_reviewer"];
export default function ForgeBase9Page(){const[providers,setProviders]=useState<Provider[]>([]);const[models,setModels]=useState<Model[]>([]);const[assignments,setAssignments]=useState<Assignment[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[pForm,setPForm]=useState({id:"",name:"9router",base_url:"https://9router.may365.cloud/v1",api_key:"",api_key_env_var:""});const[mForm,setMForm]=useState({provider_id:"",model_id:""});const[test,setTest]=useState({provider_id:"",model_id:"",prompt:"Reply with exactly: RecallOS model test OK"});const[testResult,setTestResult]=useState<Record<string,unknown>|null>(null);const[aForm,setAForm]=useState<Record<string,{provider_id:string;model_id:string}>>({});
 const load=useCallback(async()=>{setError("");try{const [p,m,a]=await Promise.all([fetch("/api/forgebase9/providers").then(r=>r.json()),fetch("/api/forgebase9/models").then(r=>r.json()),fetch("/api/forgebase9/assignments?project_id=recallos-runtime").then(r=>r.json())]); if(p.error||m.error||a.error) throw new Error(p.error||m.error||a.error); setProviders(p.providers||[]); setModels(m.models||[]); setAssignments(a.assignments||[]);}catch(e){setError(String(e));}},[]);useEffect(()=>{load();},[load]);
 const prefixes=useMemo(()=>[...new Set(models.map(m=>m.prefix).filter(Boolean))], [models]);
 const saveProvider=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/forgebase9/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(pForm)}).then(r=>r.json()); if(r.error)throw new Error(r.error); setPForm({id:"",name:"9router",base_url:"https://9router.may365.cloud/v1",api_key:"",api_key_env_var:""}); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const seed=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/forgebase9",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"seed"})}).then(r=>r.json()); if(r.error)throw new Error(r.error); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const editProvider=(p:Provider)=>{setPForm({id:p.id,name:p.name,base_url:p.base_url,api_key:"",api_key_env_var:p.api_key_env_var||""}); window.scrollTo({top:0,behavior:"smooth"});};
 const cancelEdit=()=>setPForm({id:"",name:"9router",base_url:"https://9router.may365.cloud/v1",api_key:"",api_key_env_var:""});
 const deleteProvider=async(provider_id:string,name:string)=>{if(!confirm(`Delete provider ${name}? This also deletes its models and agent assignments.`))return;setBusy(true);setError("");try{const r=await fetch("/api/forgebase9/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",provider_id})}).then(r=>r.json()); if(r.error)throw new Error(r.error); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const discover=async(provider_id:string)=>{setBusy(true);setError("");try{const r=await fetch("/api/forgebase9/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discover",provider_id})}).then(r=>r.json()); if(r.error)throw new Error(r.error); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const addModel=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/forgebase9/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(mForm)}).then(r=>r.json()); if(r.error)throw new Error(r.error); setMForm({...mForm,model_id:""}); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const runTest=async()=>{setBusy(true);setError("");setTestResult(null);try{const r=await fetch("/api/forgebase9/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(test)}).then(r=>r.json()); if(r.error)throw new Error(r.error); setTestResult(r);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const saveAssignment=async(agent_id:string)=>{const v=aForm[agent_id];if(!v?.provider_id||!v?.model_id)return;setBusy(true);setError("");try{const r=await fetch("/api/forgebase9/assignments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:"default",project_id:"recallos-runtime",agent_id,provider_id:v.provider_id,model_id:v.model_id})}).then(r=>r.json()); if(r.error)throw new Error(r.error); await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const modelsFor=(pid:string)=>models.filter(m=>m.provider_id===pid);
 return <div className="space-y-6"><PageHeader eyebrow="multi-agent control plane" title="Multi Agent" accent="violet" description="Manage ForgeBase9 endpoints, model prefixes/IDs, and multi-agent model assignments from RecallOS." actions={<button className="btn btn-primary" onClick={seed} disabled={busy}>Seed current config</button>}/>{error&&<DataCard className="border-rose-500/40 text-rose-300">{error}</DataCard>}<div className="grid gap-4 md:grid-cols-4"><MetricTile label="Providers" value={providers.length} tone="blue"/><MetricTile label="Models" value={models.length} tone="violet"/><MetricTile label="Prefixes" value={prefixes.length} tone="cyan"/><MetricTile label="Assignments" value={assignments.length} tone="green"/></div>
 <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><DataCard><SectionTitle title={pForm.id?"Edit provider":"Provider endpoints"} subtitle={pForm.id?"Re-enter raw API key or env var to enable direct model tests.":"API keys are masked; raw keys never return from API."}/>{pForm.id&&<div className="mb-3 rounded-2xl border border-violet-400/20 bg-violet-400/10 p-3 text-xs text-violet-200">Editing provider <span className="font-mono">{pForm.id}</span>. Raw API key is blank by design; paste it again to enable testing.</div>}<div className="grid gap-3"><input placeholder="Provider name" value={pForm.name} onChange={e=>setPForm({...pForm,name:e.target.value})}/><input placeholder="Base URL" value={pForm.base_url} onChange={e=>setPForm({...pForm,base_url:e.target.value})}/><input placeholder="API key (optional direct local)" type="password" value={pForm.api_key} onChange={e=>setPForm({...pForm,api_key:e.target.value})}/><input placeholder="API key env var (optional)" value={pForm.api_key_env_var} onChange={e=>setPForm({...pForm,api_key_env_var:e.target.value})}/><div className="flex gap-2"><button className="btn btn-primary" disabled={busy||!pForm.name||!pForm.base_url} onClick={saveProvider}>{pForm.id?"Update provider":"Save provider"}</button>{pForm.id&&<button className="btn btn-ghost" disabled={busy} onClick={cancelEdit}>Cancel</button>}</div></div><div className="mt-5 space-y-3">{providers.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone="blue">{p.name}</StatusPill><StatusPill tone={p.has_api_key?"green":"amber"}>{p.api_key_storage}</StatusPill><button className="btn btn-ghost ml-auto" onClick={()=>discover(p.id)} disabled={busy}>Discover models</button><button className="btn btn-ghost" onClick={()=>editProvider(p)} disabled={busy}>Edit</button><button className="btn btn-ghost text-rose-300" onClick={()=>deleteProvider(p.id,p.name)} disabled={busy}>Delete</button></div><div className="mt-2 break-all font-mono text-xs text-slate-400">{p.base_url}</div><div className="mt-1 text-xs text-slate-500">key: {p.api_key_masked||p.api_key_env_var||"not set"}</div></div>)}</div></DataCard>
 <DataCard><SectionTitle title="Model catalog" subtitle="Discover from /models or add manually."/><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select value={mForm.provider_id} onChange={e=>setMForm({...mForm,provider_id:e.target.value})}><option value="">Provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input placeholder="model id, e.g. ag/claude-opus-4-6-thinking" value={mForm.model_id} onChange={e=>setMForm({...mForm,model_id:e.target.value})}/><button className="btn btn-primary" onClick={addModel} disabled={busy||!mForm.provider_id||!mForm.model_id}>Add model</button></div><div className="mt-4 flex flex-wrap gap-2">{prefixes.map(p=><StatusPill key={p} tone="cyan">{p}</StatusPill>)}</div><div className="mt-5 grid gap-2 max-h-[420px] overflow-auto pr-1">{models.map(m=><div key={m.id} className="rounded-2xl border border-white/10 bg-black/20 p-3"><div className="flex flex-wrap gap-2"><StatusPill tone="violet">{m.provider_name||m.provider_id}</StatusPill>{m.prefix&&<StatusPill tone="cyan">{m.prefix}</StatusPill>}<span className="font-mono text-sm text-slate-200">{m.model_id}</span></div></div>)}</div></DataCard></div>
 <DataCard><SectionTitle title="Direct model test" subtitle="Calls provider/model directly through RecallOS registry, not ForgeBase9 MCP."/><div className="grid gap-3 xl:grid-cols-[1fr_1fr_2fr_auto]"><select value={test.provider_id} onChange={e=>setTest({...test,provider_id:e.target.value,model_id:modelsFor(e.target.value)[0]?.model_id||""})}><option value="">Provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={test.model_id} onChange={e=>setTest({...test,model_id:e.target.value})}><option value="">Model</option>{modelsFor(test.provider_id).map(m=><option key={m.model_id} value={m.model_id}>{m.model_id}</option>)}</select><input value={test.prompt} onChange={e=>setTest({...test,prompt:e.target.value})} placeholder="Test prompt"/><button className="btn btn-primary" disabled={busy||!test.provider_id||!test.model_id} onClick={runTest}>Test model</button></div>{testResult&&<pre className="mt-4 max-h-72 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-sm text-slate-300 whitespace-pre-wrap">{JSON.stringify(testResult,null,2)}</pre>}</DataCard>
 <DataCard glow><SectionTitle title="Multi-agent assignments" subtitle="Choose endpoint and model for each ForgeBase9 agent."/><div className="grid gap-3">{AGENTS.map(agent=>{const current=assignments.find(a=>a.agent_id===agent);const draft=aForm[agent]||{provider_id:current?.provider_id||providers[0]?.id||"",model_id:current?.model_id||""};return <div key={agent} className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4 xl:grid-cols-[260px_1fr_1fr_auto]"><div><div className="font-black text-slate-100">{agent}</div><div className="text-xs text-slate-500">current: {current?`${current.provider_name} · ${current.model_id}`:"not assigned"}</div></div><select value={draft.provider_id} onChange={e=>{const provider_id=e.target.value;setAForm({...aForm,[agent]:{provider_id,model_id:modelsFor(provider_id)[0]?.model_id||""}})}}><option value="">Provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={draft.model_id} onChange={e=>setAForm({...aForm,[agent]:{...draft,model_id:e.target.value}})}><option value="">Model</option>{modelsFor(draft.provider_id).map(m=><option key={m.model_id} value={m.model_id}>{m.model_id}</option>)}</select><button className="btn btn-primary" disabled={busy||!draft.provider_id||!draft.model_id} onClick={()=>saveAssignment(agent)}>Save</button></div>})}</div></DataCard></div>}
