"use client";
import { useEffect, useState, useCallback } from "react";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";

interface MemEvent { id: string; session_id: string; actor: string; event_type: string; content: string; agent_id?: string; task_id?: string; run_id?: string; created_at: string; }
interface MemFact { id: string; scope: string; key: string; value: string; confidence: number; agent_id?: string; pair_key?: string; task_id?: string; session_id?: string; run_id?: string; updated_at: string; }
interface Chunk { id: string; source_type: string; source_id?: string; text: string; metadata: Record<string, unknown>; created_at: string; has_embedding: boolean; }
interface Link { id: string; source_id: string; target_id: string; relation: string; metadata: Record<string, unknown>; created_at: string; }
interface Counts { events: number; facts: number; chunks: number; links: number; embedded_chunks: number; handoffs?: number; agent_messages?: number; pair_memories?: number; workflow_runs?: number; }
interface Layer { id: string; name: string; count: number; description: string; }
interface Dist { scope?: string; event_type?: string; actor?: string; session_id?: string; count: number; last_seen?: string; }
interface PairMemory { id: string; pair_key: string; agent_a: string; agent_b: string; type: string; title?: string; content: string; importance: number; status: string; updated_at: string; }
interface PairRow { pair_key: string; agent_a: string; agent_b: string; count: number; last_updated: string; }
const TABS = ["Raw Events", "Active Facts", "Context Chunks", "Working Memory", "Pair Memory", "Workflows", "Search"];

export default function MemoryPage() {
  const [tab, setTab] = useState("Raw Events");
  const [events, setEvents] = useState<MemEvent[]>([]); const [facts, setFacts] = useState<MemFact[]>([]); const [chunks, setChunks] = useState<Chunk[]>([]); const [links, setLinks] = useState<Link[]>([]);
  const [counts, setCounts] = useState<Counts>({ events: 0, facts: 0, chunks: 0, links: 0, embedded_chunks: 0 });
  const [layers, setLayers] = useState<Layer[]>([]); const [scopes, setScopes] = useState<Dist[]>([]); const [eventTypes, setEventTypes] = useState<Dist[]>([]); const [actors, setActors] = useState<Dist[]>([]); const [sessions, setSessions] = useState<Dist[]>([]);
  const [pairs, setPairs] = useState<PairRow[]>([]); const [pairMemories, setPairMemories] = useState<PairMemory[]>([]); const [workflows, setWorkflows] = useState<{runs: Array<{run_id:string;handoffs:number;last_seen:string}>; handoffs: Array<Record<string, unknown>>; messages: Array<Record<string, unknown>>}>({runs:[],handoffs:[],messages:[]});
  const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const fetchData = useCallback((q = "") => { setLoading(true); setError(""); const params = new URLSearchParams(); if (q) params.set("query", q); Promise.all([fetch(`/api/memory?${params}`).then(r=>r.json()), fetch(`/api/pair-memory?${params}`).then(r=>r.json()), fetch(`/api/workflows`).then(r=>r.json())]).then(([d,p,w])=>{ if(d.error) setError(d.error); setEvents(d.events||[]); setFacts(d.facts||[]); setChunks(d.chunks||[]); setLinks(d.links||[]); setCounts(d.counts||{}); setLayers(d.layers||[]); setScopes(d.scopes||[]); setEventTypes(d.eventTypes||[]); setActors(d.actors||[]); setSessions(d.sessions||[]); setPairs(p.pairs||[]); setPairMemories(p.memories||[]); setWorkflows(w||{runs:[],handoffs:[],messages:[]}); setLoading(false); }).catch(e=>{ setError(String(e)); setLoading(false); }); }, []);
  useEffect(() => { fetchData(); }, [fetchData]);
  const handleSearch = () => { setTab("Search"); fetchData(query); };
  const embedPct = counts.chunks ? Math.round((counts.embedded_chunks / counts.chunks) * 100) : 0;
  return <div className="space-y-6">
    <PageHeader eyebrow="four-layer memory" title="Memory Cockpit" accent="violet" description="Inspect raw events, active facts, vector chunks, working links, Pair Memory, and ForgeBase9 workflow traces." actions={<StatusPill tone="violet">{pairMemories.length} pair memories</StatusPill>} />
    {error && <DataCard className="border-rose-500/40 text-rose-300">{error}</DataCard>}
    <div className="grid gap-4 md:grid-cols-4 xl:grid-cols-8"><MetricTile label="Events" value={counts.events} tone="blue"/><MetricTile label="Facts" value={counts.facts} tone="green"/><MetricTile label="Chunks" value={counts.chunks} tone="violet"/><MetricTile label="Vectors" value={counts.embedded_chunks} tone="cyan"/><MetricTile label="Handoffs" value={counts.handoffs||0} tone="amber"/><MetricTile label="Messages" value={counts.agent_messages||0} tone="blue"/><MetricTile label="Pair Memory" value={counts.pair_memories||0} tone="rose"/><MetricTile label="Runs" value={counts.workflow_runs||0} tone="green"/></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_.8fr]">
      <DataCard><SectionTitle title="Memory pressure" subtitle="Embedding coverage and layer distribution"/><div className="grid gap-3 md:grid-cols-4">{layers.map((l,i)=><div key={l.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><div className="flex items-center justify-between"><StatusPill tone="violet">L{i+1}</StatusPill><span className="metric-value text-2xl font-black text-violet-200">{l.count}</span></div><h3 className="mt-3 text-sm font-black text-slate-100">{l.name}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{l.description}</p></div>)}</div><div className="mt-5 confidence-bar"><span style={{ width: `${embedPct}%` }} /></div><div className="mt-2 text-xs text-slate-400">Vector coverage {embedPct}% · {counts.embedded_chunks}/{counts.chunks} chunks</div></DataCard>
      <DataCard><SectionTitle title="Runtime facets" subtitle="Scopes, actors, sessions"/><div className="space-y-4"><div className="flex flex-wrap gap-2">{scopes.map(s=><StatusPill key={s.scope} tone="blue">{s.scope}: {s.count}</StatusPill>)}</div><div className="flex flex-wrap gap-2">{eventTypes.map(e=><StatusPill key={e.event_type} tone="gray">{e.event_type}: {e.count}</StatusPill>)}</div><div className="flex flex-wrap gap-2">{actors.map(a=><StatusPill key={a.actor} tone="green">{a.actor}: {a.count}</StatusPill>)}</div><div className="space-y-1 text-xs text-slate-500">{sessions.slice(0,5).map(s=><div key={s.session_id} className="truncate font-mono">{s.session_id}: {s.count}</div>)}</div></div></DataCard>
    </div>
    <CommandBar><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-1 rounded-2xl bg-black/20 p-1">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`tab ${tab===t?"active":""}`}>{t}</button>)}</div><div className="flex flex-1 gap-2 lg:ml-auto"><input type="text" placeholder="Search memory, pair protocols, workflows..." value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&handleSearch()} /><button onClick={handleSearch} className="btn btn-primary">Search</button></div></div></CommandBar>
    {loading ? <div className="skeleton h-40" /> : <div className="space-y-5">
      {(tab==="Raw Events"||tab==="Search") && <Stream title={`Layer A · Raw Events (${events.length})`}>{events.map(e=><DataCard key={e.id} className="py-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone="blue">{e.event_type}</StatusPill><StatusPill tone="gray">{e.actor}</StatusPill>{e.agent_id&&<StatusPill tone="green">{e.agent_id}</StatusPill>}<span className="ml-auto text-xs text-slate-500">{new Date(e.created_at).toLocaleString()}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{e.content}</p><div className="mt-3 font-mono text-xs text-slate-500">session={e.session_id} task={e.task_id||"-"} run={e.run_id||"-"}</div></DataCard>)}</Stream>}
      {(tab==="Active Facts"||tab==="Search") && <Stream title={`Layer B · Active Facts (${facts.length})`}>{facts.map(f=><DataCard key={f.id} className="py-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone="green">{f.scope}</StatusPill><span className="font-mono text-sm text-blue-300">{f.key}</span><span className="ml-auto text-xs text-slate-500">conf {f.confidence}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{f.value}</p><div className="mt-3 confidence-bar"><span style={{ width: `${Math.round((f.confidence||0)*100)}%` }} /></div></DataCard>)}</Stream>}
      {(tab==="Context Chunks"||tab==="Search") && <Stream title={`Layer C · Context Chunks (${chunks.length})`}>{chunks.map(c=><DataCard key={c.id} className="py-4"><div className="flex items-center gap-2"><StatusPill tone="violet">{c.source_type}</StatusPill><StatusPill tone={c.has_embedding?"green":"red"}>{c.has_embedding?"embedded":"no vector"}</StatusPill><span className="ml-auto text-xs text-slate-500">{new Date(c.created_at).toLocaleString()}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{c.text}</p></DataCard>)}</Stream>}
      {(tab==="Working Memory"||tab==="Search") && <Stream title={`Layer D · Working Links (${links.length})`}>{links.map(l=><DataCard key={l.id} className="py-4"><StatusPill tone="amber">{l.relation}</StatusPill><div className="mt-3 break-all font-mono text-xs text-slate-400">{l.source_id} → {l.target_id}</div></DataCard>)}{links.length===0&&<EmptyState title="Working graph empty" description="No active relations stored yet."/>}</Stream>}
      {tab==="Pair Memory" && <PairMemoryView pairs={pairs} memories={pairMemories}/>} 
      {tab==="Workflows" && <WorkflowView workflows={workflows}/>} 
    </div>}
  </div>;
}
function Stream({ title, children }: { title: string; children: React.ReactNode }) { return <section><SectionTitle title={title}/><div className="grid gap-3">{children}</div></section>; }
function PairMemoryView({pairs,memories}:{pairs:PairRow[];memories:PairMemory[]}){return <div className="grid gap-4 xl:grid-cols-[320px_1fr]"><DataCard><SectionTitle title="Agent pairs" subtitle="Collaboration memory index"/><div className="space-y-2">{pairs.map(p=><div key={p.pair_key} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div className="font-mono text-sm text-violet-200">{p.pair_key}</div><div className="mt-1 text-xs text-slate-500">{p.count} memories · {new Date(p.last_updated).toLocaleString()}</div></div>)}</div></DataCard><Stream title={`Pair Memory Cards (${memories.length})`}>{memories.map(m=><DataCard key={m.id}><div className="flex flex-wrap gap-2"><StatusPill tone="violet">{m.pair_key}</StatusPill><StatusPill tone="amber">{m.type}</StatusPill><StatusPill tone={m.status==="active"?"green":"gray"}>{m.status}</StatusPill><span className="ml-auto text-xs text-slate-500">importance {m.importance}</span></div><h3 className="mt-3 font-black text-slate-100">{m.title||m.type}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{m.content}</p></DataCard>)}</Stream></div>}
function WorkflowView({workflows}:{workflows:{runs:Array<{run_id:string;handoffs:number;last_seen:string}>;handoffs:Array<Record<string,unknown>>;messages:Array<Record<string,unknown>>}}){return <div className="grid gap-4 xl:grid-cols-[320px_1fr]"><DataCard><SectionTitle title="Runs"/><div className="space-y-2">{workflows.runs.map(r=><div key={r.run_id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div className="truncate font-mono text-xs text-cyan-200">{r.run_id}</div><div className="mt-1 text-xs text-slate-500">{r.handoffs} handoffs · {new Date(r.last_seen).toLocaleString()}</div></div>)}</div></DataCard><div className="space-y-4"><Stream title={`Handoffs (${workflows.handoffs.length})`}>{workflows.handoffs.map((h,i)=><DataCard key={String(h.id||i)}><div className="flex flex-wrap gap-2"><StatusPill tone="blue">{String(h.from_agent_id)} → {String(h.to_agent_id)}</StatusPill><StatusPill tone="green">{String(h.status)}</StatusPill></div><h3 className="mt-3 font-bold text-slate-100">{String(h.task_title)}</h3><p className="mt-2 text-sm text-slate-400">{String(h.result_summary||"")}</p></DataCard>)}</Stream><Stream title={`Messages (${workflows.messages.length})`}>{workflows.messages.slice(0,10).map((m,i)=><DataCard key={String(m.id||i)}><StatusPill tone="gray">{String(m.from_agent_id)} → {String(m.to_agent_id)}</StatusPill><p className="mt-3 text-sm text-slate-300">{String(m.content||"")}</p></DataCard>)}</Stream></div></div>}
