"use client";
import { useEffect, useState, useCallback } from "react";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";

interface Node { id: string; kind: string; name: string; qualified_name: string; file_path: string; language: string; start_line: number; end_line: number; signature?: string; docstring?: string; is_exported: number; is_async: number; }
interface Edge { kind: string; source_name: string; source_file: string; target_name: string; target_file: string; line: number; col: number; }
interface CountRow { files: number; nodes: number; edges: number; unresolved_refs: number; }
interface Dist { kind?: string; language?: string; count: number; }
interface TopFile { path: string; language: string; size: number; node_count: number; errors?: string | null; }
function tone(value: string): "blue" | "green" | "red" | "gray" | "cyan" | "violet" { if (["function","calls"].includes(value)) return "blue"; if (["interface","imports"].includes(value)) return "green"; if (value.includes("unresolved")) return "red"; if (value === "class") return "violet"; if (value === "file") return "cyan"; return "gray"; }
export default function CodeGraphPage() {
  const [query,setQuery]=useState(""); const [kindFilter,setKindFilter]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [dbPath,setDbPath]=useState(""); const [counts,setCounts]=useState<CountRow|null>(null); const [kinds,setKinds]=useState<Dist[]>([]); const [languages,setLanguages]=useState<Dist[]>([]); const [edgeKinds,setEdgeKinds]=useState<Dist[]>([]); const [topFiles,setTopFiles]=useState<TopFile[]>([]); const [nodes,setNodes]=useState<Node[]>([]); const [edges,setEdges]=useState<Edge[]>([]);
  const load=useCallback(()=>{ setLoading(true); setError(""); const params=new URLSearchParams(); if(query) params.set("query",query); if(kindFilter) params.set("kind",kindFilter); fetch(`/api/codegraph?${params}`).then(r=>r.json()).then(d=>{ if(d.error) setError(d.error); setDbPath(d.dbPath||""); setCounts(d.counts||null); setKinds(d.kinds||[]); setLanguages(d.languages||[]); setEdgeKinds(d.edgeKinds||[]); setTopFiles(d.topFiles||[]); setNodes(d.nodes||[]); setEdges(d.relatedEdges||[]); setLoading(false); }).catch(e=>{setError(String(e)); setLoading(false);}); },[query,kindFilter]);
  useEffect(()=>{load();},[load]);
  return <div className="space-y-6"><PageHeader eyebrow="source intelligence" title="CodeGraph Explorer" accent="cyan" description="Traverse files, symbols, imports, calls, references, and impact surfaces from the local SQLite graph." actions={<StatusPill tone={counts?"cyan":"gray"}>{counts?`${counts.nodes} nodes`:"loading"}</StatusPill>} />{error&&<DataCard className="border-rose-500/40 text-rose-300">{error}</DataCard>}
    {counts&&<div className="grid gap-4 md:grid-cols-4"><MetricTile label="Files" value={counts.files} tone="cyan"/><MetricTile label="Nodes" value={counts.nodes} tone="violet"/><MetricTile label="Edges" value={counts.edges} tone="green"/><MetricTile label="Unresolved" value={counts.unresolved_refs} tone="rose"/></div>}
    <CommandBar><div className="grid gap-3 md:grid-cols-[1fr_210px_auto]"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search symbols, files, signatures..."/><select value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">All kinds</option>{kinds.map(k=><option key={k.kind} value={k.kind}>{k.kind}</option>)}</select><button onClick={load} className="btn btn-primary">Trace graph</button></div><div className="mt-3 truncate font-mono text-xs text-slate-500">{dbPath}</div></CommandBar>
    <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><DataCard><SectionTitle title="Graph controls" subtitle="Filter by symbol kind, language, edge type"/><div className="space-y-4"><div className="flex flex-wrap gap-2">{kinds.map(k=><button key={k.kind} onClick={()=>setKindFilter(k.kind||"")} className={`badge ${tone(k.kind||"")}`}>{k.kind}: {k.count}</button>)}</div><div className="flex flex-wrap gap-2">{languages.map(l=><StatusPill key={l.language} tone="cyan">{l.language}: {l.count}</StatusPill>)}</div><div className="flex flex-wrap gap-2">{edgeKinds.map(e=><StatusPill key={e.kind} tone={tone(e.kind||"")}>{e.kind}: {e.count}</StatusPill>)}</div></div></DataCard><DataCard><SectionTitle title="Top files"/><div className="space-y-2 max-h-[420px] overflow-auto">{topFiles.map(f=><div key={f.path} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div className="text-sm text-slate-200">{f.path}</div><div className="mt-1 font-mono text-xs text-slate-500">{f.language} · {f.node_count} nodes · {Math.round(f.size/1024)}KB</div></div>)}</div></DataCard></div>
      <DataCard glow><SectionTitle title="Symbol browser" subtitle="Click filters left to narrow the graph"/>{loading&&<div className="skeleton h-32"/>}<div className="space-y-3 max-h-[760px] overflow-auto pr-1">{nodes.map(n=><div key={n.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={tone(n.kind)}>{n.kind}</StatusPill>{n.is_async?<StatusPill tone="blue">async</StatusPill>:null}{n.is_exported?<StatusPill tone="green">export</StatusPill>:null}<span className="ml-auto font-mono text-xs text-slate-500">L{n.start_line}-{n.end_line}</span></div><div className="mt-3 font-bold text-slate-100">{n.qualified_name||n.name}</div><div className="mt-1 font-mono text-xs text-cyan-300">{n.file_path}</div>{n.signature&&<pre className="mt-3 overflow-auto rounded-xl border border-white/10 bg-[#07101f] p-3 text-xs text-slate-300">{n.signature}</pre>}</div>)}{nodes.length===0&&!loading&&<EmptyState title="No symbols" description="Try a wider query or clear filters."/>}</div></DataCard></div>
    <DataCard><SectionTitle title="Related edges" subtitle="Observed relationships around current result set"/><div className="grid gap-2 md:grid-cols-2">{edges.map((e,i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><StatusPill tone={tone(e.kind)}>{e.kind}</StatusPill><div className="mt-2 text-sm text-slate-300">{e.source_name} → {e.target_name}</div><div className="mt-1 truncate font-mono text-xs text-slate-500">{e.source_file||e.target_file}</div></div>)}</div></DataCard>
  </div>;
}
