"use client";
import { useState } from "react";
import dynamic from "next/dynamic";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";
const MonacoEditor = dynamic(() => import("@monaco-editor/react"), { ssr: false });
interface Section { source: string; title: string; content: string; tokens: number; }
const AGENTS=["","assistant","architect","secretary","coder","designer","reviewer"]; const DEPTHS=["full","summary","minimal"];
const sourceTone:Record<string,"blue"|"green"|"amber"|"cyan"|"violet"|"gray">={"Project Brain":"blue",Memory:"green","Knowledge Base":"amber",CodeGraph:"cyan",Agents:"violet"};
export default function ContextPackPage(){ const [task,setTask]=useState(""); const [agentId,setAgentId]=useState(""); const [depth,setDepth]=useState("full"); const [symbols,setSymbols]=useState(""); const [loading,setLoading]=useState(false); const [result,setResult]=useState<{sections:Section[]; totalTokens:number; sources:string[]; finalMarkdown:string}|null>(null);
 const buildContext=async()=>{ if(!task.trim()) return; setLoading(true); try{ const res=await fetch("/api/context-pack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,agent_id:agentId||undefined,depth,symbols:symbols?symbols.split(",").map(s=>s.trim()):undefined})}); setResult(await res.json()); }catch{} setLoading(false); };
 return <div className="space-y-6"><PageHeader eyebrow="context orchestration" title="Context Pack Composer" accent="violet" description="Assemble task-specific context bundles from Project Brain, Memory, Knowledge Base, CodeGraph, and agent state." actions={<StatusPill tone="violet">composer mode</StatusPill>}/>
 <CommandBar><div className="grid gap-3 xl:grid-cols-[1fr_160px_160px_1fr_auto]"><input placeholder="Task, e.g. fix memory recall bug" value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&buildContext()}/><select value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Agent: none</option>{AGENTS.filter(Boolean).map(a=><option key={a} value={a}>{a}</option>)}</select><select value={depth} onChange={e=>setDepth(e.target.value)}>{DEPTHS.map(d=><option key={d} value={d}>Depth: {d}</option>)}</select><input placeholder="symbols: foo, bar" value={symbols} onChange={e=>setSymbols(e.target.value)}/><button onClick={buildContext} disabled={!task.trim()||loading} className="btn btn-primary">{loading?"Building":"Build pack"}</button></div></CommandBar>
 {loading&&<div className="skeleton h-40"/>}
 {result&&<><div className="grid gap-4 md:grid-cols-4"><MetricTile label="Sections" value={result.sections.length} tone="violet"/><MetricTile label="Tokens" value={`~${result.totalTokens}`} tone="blue"/><MetricTile label="Sources" value={result.sources.length} tone="green"/><MetricTile label="Depth" value={depth} tone="amber"/></div><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><DataCard><SectionTitle title="Source deck" subtitle="Context bundle composition"/><div className="space-y-3">{result.sources.map(src=>{const secs=result.sections.filter(s=>s.source===src); const toks=secs.reduce((sum,s)=>sum+s.tokens,0); return <div key={src} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><StatusPill tone={sourceTone[src]||"gray"}>{src}</StatusPill><span className="metric-value font-black text-slate-200">{secs.length}</span></div><div className="mt-3 confidence-bar"><span style={{width:`${Math.min(100,Math.round((toks/Math.max(result.totalTokens,1))*100))}%`}}/></div><div className="mt-2 text-xs text-slate-500">~{toks} tokens</div></div>})}</div></DataCard><DataCard glow><SectionTitle title="Sections" subtitle="Preview of assembled cards"/><div className="grid gap-3 max-h-[560px] overflow-auto pr-1">{result.sections.map((s,i)=><div key={i} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-2"><StatusPill tone={sourceTone[s.source]||"gray"}>{s.source}</StatusPill><span className="ml-auto font-mono text-xs text-slate-500">~{s.tokens} tok</span></div><h3 className="mt-3 font-black text-slate-100">{s.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-400">{s.content.slice(0,260)}{s.content.length>260?"...":""}</p></div>)}</div></DataCard></div><DataCard><SectionTitle title="Final Context Markdown" subtitle="Read-only generated pack"/><div className="overflow-hidden rounded-2xl border border-white/10" style={{height:540}}><MonacoEditor height="100%" defaultLanguage="markdown" value={result.finalMarkdown} theme="vs-dark" options={{readOnly:true,minimap:{enabled:false},fontSize:13,wordWrap:"on",lineNumbers:"off",scrollBeyondLastLine:false,padding:{top:14}}}/></div></DataCard></>}
 {!result&&!loading&&<EmptyState icon="◆" title="No active context pack" description="Enter a task and build a pack to see RecallOS assemble agent-ready context."/>}
 </div>; }
