"use client";
import { useState } from "react";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";
interface Section { source: string; title: string; content: string; tokens: number; }
const AGENTS=["","assistant","pm_architecture","analyzer","coder","designer","reviewer"]; const DEPTHS=["full","summary","minimal"];
const sourceTone:Record<string,"blue"|"green"|"amber"|"cyan"|"violet"|"gray">={"Project Brain":"blue",Memory:"green","Knowledge Base":"amber",CodeGraph:"cyan",Agents:"violet","Session Resume":"violet"};
export default function ContextPackPage(){ const [task,setTask]=useState(""); const [agentId,setAgentId]=useState(""); const [depth,setDepth]=useState("full"); const [symbols,setSymbols]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<{sections:Section[]; totalTokens:number; sources:string[]; finalMarkdown:string; meta?:Record<string,unknown>}|null>(null);
 const buildContext=async()=>{ if(!task.trim()) return; setLoading(true); setError(""); setResult(null); try{ const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),30000); const res=await fetch("/api/context-pack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,agent_id:agentId||undefined,depth,symbols:symbols?symbols.split(",").map(s=>s.trim()).filter(Boolean):undefined}),signal:controller.signal}); clearTimeout(timer); const json=await res.json(); if(!res.ok||json.error){setError(json.error||`HTTP ${res.status}`); return;} setResult(json); }catch(e){ setError(e instanceof Error && e.name==="AbortError" ? "Context build timed out after 30s" : String(e)); } finally { setLoading(false); } };
 return <div className="space-y-6"><PageHeader eyebrow="context orchestration" title="Context Pack Composer" accent="violet" description="Preview the same RecallOS context engine ForgeBase9 agents use. Actual agent calls may add run_id, task_id, pair memory, session resume, and work contract." actions={<StatusPill tone="violet">runtime composer</StatusPill>}/>
 <DataCard><SectionTitle title="What this page does" subtitle="Context packs are generated on demand, not stored as a database table."/><div className="grid gap-3 md:grid-cols-3 text-sm text-slate-300"><p><b className="text-slate-100">Same engine:</b> uses RecallOS context-orchestrator logic that agents call before work.</p><p><b className="text-slate-100">Preview mode:</b> dashboard params can differ from production agent calls.</p><p><b className="text-slate-100">Sources:</b> Project Brain, 4-Layer Memory, Session Resume, Pair Memory/Agents, KB, CodeGraph.</p></div></DataCard>
 <CommandBar><div className="grid gap-3 xl:grid-cols-[1fr_180px_160px_1fr_auto]"><input placeholder="Task, e.g. fix memory recall bug" value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&buildContext()}/><select value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Agent: none</option>{AGENTS.filter(Boolean).map(a=><option key={a} value={a}>{a}</option>)}</select><select value={depth} onChange={e=>setDepth(e.target.value)}>{DEPTHS.map(d=><option key={d} value={d}>Depth: {d}</option>)}</select><input placeholder="symbols: foo, bar" value={symbols} onChange={e=>setSymbols(e.target.value)}/><button onClick={buildContext} disabled={!task.trim()||loading} className="btn btn-primary">{loading?"Building":"Build pack"}</button></div></CommandBar>
 {error&&<DataCard className="border-rose-500/40 text-rose-300"><SectionTitle title="Build failed"/><pre className="whitespace-pre-wrap text-sm">{error}</pre></DataCard>}
 {loading&&<DataCard><SectionTitle title="Final Context Markdown" subtitle="Generating pack from live RecallOS sources"/><div className="skeleton h-40"/><p className="mt-3 text-sm text-slate-400">Loading context. If this lasts over 30 seconds, request will fail with visible error.</p></DataCard>}
 {result&&<><div className="grid gap-4 md:grid-cols-5"><MetricTile label="Sections" value={result.sections.length} tone="violet"/><MetricTile label="Tokens" value={`~${result.totalTokens}`} tone="blue"/><MetricTile label="Sources" value={result.sources.length} tone="green"/><MetricTile label="Depth" value={depth} tone="amber"/><MetricTile label="Chars" value={result.finalMarkdown.length} tone="cyan"/></div><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><DataCard><SectionTitle title="Source deck" subtitle="Context bundle composition"/><div className="space-y-3">{result.sources.map(src=>{const secs=result.sections.filter(s=>s.source===src); const toks=secs.reduce((sum,s)=>sum+s.tokens,0); return <div key={src} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><StatusPill tone={sourceTone[src]||"gray"}>{src}</StatusPill><span className="metric-value font-black text-slate-200">{secs.length}</span></div><div className="mt-3 confidence-bar"><span style={{width:`${Math.min(100,Math.round((toks/Math.max(result.totalTokens,1))*100))}%`}}/></div><div className="mt-2 text-xs text-slate-500">~{toks} tokens</div></div>})}</div></DataCard><DataCard glow><SectionTitle title="Sections" subtitle="Preview of assembled cards"/><div className="grid gap-3 max-h-[560px] overflow-auto pr-1">{result.sections.length?result.sections.map((s,i)=><div key={i} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-2"><StatusPill tone={sourceTone[s.source]||"gray"}>{s.source}</StatusPill><span className="ml-auto font-mono text-xs text-slate-500">~{s.tokens} tok</span></div><h3 className="mt-3 font-black text-slate-100">{s.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-400">{s.content.slice(0,260)}{s.content.length>260?"...":""}</p></div>):<EmptyState title="No sections found" description="The pack built successfully but no sources matched this task."/>}</div></DataCard></div><DataCard><SectionTitle title="Final Context Markdown" subtitle="Read-only generated pack"/><pre className="max-h-[540px] overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-sm leading-6 text-slate-300 whitespace-pre-wrap">{result.finalMarkdown||"No markdown generated."}</pre></DataCard></>}
 {!result&&!loading&&!error&&<EmptyState icon="◆" title="No active context pack" description="Enter a task and build a pack to see RecallOS assemble agent-ready context."/>}
 </div>; }
