"use client";
import { useState } from "react";
import { CommandBar, DataCard, EmptyState, MetricTile, PageHeader, SectionTitle, StatusPill } from "../components/ui";
interface Section { source: string; title: string; content: string; tokens: number; }
interface SourceDetail { name:string; count:number; tokens:number; status:"hit"|"empty"|"skipped"; warnings:string[]; }
const AGENTS=["","assistant","pm_architecture","analyzer","senior_product_designer","senior_product_coder","product_code_reviewer"]; const DEPTHS=["full","summary","minimal"]; const MODES=["pack","agent","task","handoff","pair"];
const sourceTone:Record<string,"blue"|"green"|"amber"|"cyan"|"violet"|"gray">={"Project Brain":"blue",Memory:"green","Knowledge Base":"amber",CodeGraph:"cyan",Agents:"violet","Session Resume":"violet",Handoff:"amber","Pair Memory":"cyan"};
export default function ContextPackPage(){ const [task,setTask]=useState(""); const [agentId,setAgentId]=useState(""); const [depth,setDepth]=useState("full"); const [mode,setMode]=useState("pack"); const [symbols,setSymbols]=useState(""); const [fromAgent,setFromAgent]=useState("pm_architecture"); const [toAgent,setToAgent]=useState("senior_product_coder"); const [handoffId,setHandoffId]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<{mode:string;sections:Section[]; sourceDetails:SourceDetail[]; totalTokens:number; sources:string[]; finalMarkdown:string;}|null>(null);
 const buildContext=async()=>{ if(!task.trim()) return; setLoading(true); setError(""); setResult(null); try{ const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),30000); const res=await fetch("/api/context-pack",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,mode,agent_id:agentId||undefined,depth,symbols:symbols?symbols.split(",").map(s=>s.trim()).filter(Boolean):undefined,from_agent_id:fromAgent||undefined,to_agent_id:toAgent||undefined,handoff_id:handoffId||undefined}),signal:controller.signal}); clearTimeout(timer); const json=await res.json(); if(!res.ok||json.error){setError(json.error||`HTTP ${res.status}`); return;} setResult(json); }catch(e){ setError(e instanceof Error && e.name==="AbortError" ? "Context build timed out after 30s" : String(e)); } finally { setLoading(false); } };
 return <div className="space-y-6"><PageHeader eyebrow="context orchestration" title="Context Pack Viewer" accent="violet" description="Build and inspect RecallOS context by mode: general pack, agent, task, handoff, or pair." actions={<StatusPill tone="violet">runtime composer</StatusPill>}/>
 <DataCard><SectionTitle title="What this page does" subtitle="Context packs are generated on demand, not stored as a database table."/><div className="grid gap-3 md:grid-cols-3 text-sm text-slate-300"><p><b className="text-slate-100">Viewer modes:</b> pack, agent, task, handoff, and pair context.</p><p><b className="text-slate-100">Source trace:</b> shows section counts, token estimates, and empty-source warnings.</p><p><b className="text-slate-100">Preview mode:</b> production agent calls may add run_id, task_id, pair memory, and work contract.</p></div></DataCard>
 <CommandBar><div className="grid gap-3 xl:grid-cols-[1fr_150px_180px_150px_1fr_auto]"><input placeholder="Task, e.g. fix memory recall bug" value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&buildContext()}/><select value={mode} onChange={e=>setMode(e.target.value)}>{MODES.map(m=><option key={m} value={m}>Mode: {m}</option>)}</select><select value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Agent: none</option>{AGENTS.filter(Boolean).map(a=><option key={a} value={a}>{a}</option>)}</select><select value={depth} onChange={e=>setDepth(e.target.value)}>{DEPTHS.map(d=><option key={d} value={d}>Depth: {d}</option>)}</select><input placeholder="symbols: foo, bar" value={symbols} onChange={e=>setSymbols(e.target.value)}/><button onClick={buildContext} disabled={!task.trim()||loading} className="btn btn-primary">{loading?"Building":"Build"}</button></div>{mode==="pair"&&<div className="mt-3 grid gap-3 md:grid-cols-2"><input value={fromAgent} onChange={e=>setFromAgent(e.target.value)} placeholder="from agent"/><input value={toAgent} onChange={e=>setToAgent(e.target.value)} placeholder="to agent"/></div>}{mode==="handoff"&&<div className="mt-3"><input value={handoffId} onChange={e=>setHandoffId(e.target.value)} placeholder="handoff id (optional, latest if blank)"/></div>}</CommandBar>
 {error&&<DataCard className="border-rose-500/40 text-rose-300"><SectionTitle title="Build failed"/><pre className="whitespace-pre-wrap text-sm">{error}</pre></DataCard>}
 {loading&&<DataCard><SectionTitle title="Final Context Markdown" subtitle="Generating pack from live RecallOS sources"/><div className="skeleton h-40"/><p className="mt-3 text-sm text-slate-400">Loading context. If this lasts over 30 seconds, request will fail with visible error.</p></DataCard>}
 {result&&<><div className="grid gap-4 md:grid-cols-5"><MetricTile label="Mode" value={result.mode} tone="violet"/><MetricTile label="Sections" value={result.sections.length} tone="violet"/><MetricTile label="Tokens" value={`~${result.totalTokens}`} tone="blue"/><MetricTile label="Sources hit" value={result.sources.length} tone="green"/><MetricTile label="Chars" value={result.finalMarkdown.length} tone="cyan"/></div><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><DataCard><SectionTitle title="Source trace" subtitle="Where context came from"/><div className="space-y-3">{result.sourceDetails.map(src=><div key={src.name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><StatusPill tone={sourceTone[src.name]||"gray"}>{src.name}</StatusPill><span className={`text-xs ${src.status==="hit"?"text-emerald-300":"text-amber-300"}`}>{src.status}</span></div><div className="mt-3 confidence-bar"><span style={{width:`${Math.min(100,Math.round((src.tokens/Math.max(result.totalTokens,1))*100))}%`}}/></div><div className="mt-2 text-xs text-slate-500">{src.count} sections · ~{src.tokens} tokens</div>{src.warnings.map(w=><div key={w} className="mt-2 text-xs text-amber-300">⚠ {w}</div>)}</div>)}</div></DataCard><DataCard glow><SectionTitle title="Sections" subtitle="Preview of assembled cards"/><div className="grid gap-3 max-h-[560px] overflow-auto pr-1">{result.sections.length?result.sections.map((s,i)=><div key={i} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center gap-2"><StatusPill tone={sourceTone[s.source]||"gray"}>{s.source}</StatusPill><span className="ml-auto font-mono text-xs text-slate-500">~{s.tokens} tok</span></div><h3 className="mt-3 font-black text-slate-100">{s.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-400">{s.content.slice(0,320)}{s.content.length>320?"...":""}</p></div>):<EmptyState title="No sections found" description="The pack built successfully but no sources matched this task."/>}</div></DataCard></div><DataCard><SectionTitle title="Final Context Markdown" subtitle="Read-only generated pack"/><pre className="max-h-[540px] overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-sm leading-6 text-slate-300 whitespace-pre-wrap">{result.finalMarkdown||"No markdown generated."}</pre></DataCard></>}
 {!result&&!loading&&!error&&<EmptyState icon="◆" title="No active context pack" description="Enter a task and build a pack to inspect RecallOS context sources."/>}
 </div>; }
